"""Domain models for revision execution and verification."""

from pydantic import BaseModel, Field
from rightforge.models.revision import RevisionPlan


class RevisionExecutionResult(BaseModel):
    """Result of an automated style-conditioned revision execution and verification."""

    document_id: str | None = None
    original_text: str = Field(..., description="Original input text prior to revision")
    revised_text: str = Field(..., description="Transformed text generated by the revision model")
    plan: RevisionPlan = Field(..., description="The revision strategy and diagnostics that guided the model")
    consistency_before: float | None = Field(
        default=None, description="Author consistency score before revision (if profile provided)"
    )
    consistency_after: float | None = Field(
        default=None, description="Author consistency score after revision (if profile provided)"
    )
    metrics_before: dict[str, float] = Field(
        default_factory=dict, description="Key surface and linguistic metrics prior to revision"
    )
    metrics_after: dict[str, float] = Field(
        default_factory=dict, description="Key surface and linguistic metrics following revision"
    )
    success: bool = Field(default=True, description="Whether revision execution completed successfully")
    error_message: str | None = Field(
        default=None, description="Error message if execution failed or provider was unreachable"
    )
